### ISSUE TITLE
Refactor out Account structure in SAFE Core

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#777]
After refactoring out Authenticator-only functionality from Client into AuthClient, several fields of the Account struct – access_container, config_root, and root_dirs_created – are only used by AuthClient, and should be moved to AuthInner.

As this will only leave the maid_keys field in Account, we should consider removing it and making its member methods standalone functions.

One caveat is the encrypt function, which is used to store the access container and config dir as part of the account packet. We should look into where and how to store them instead.

**Comment by nbaksalyar** [comment]
> several fields of the Account struct – access_container, config_root, and root_dirs_created – are only used by AuthClient

This is fine at the present moment because we want to maintain backwards compatibility with the data & accounts stored on the Alpha 2 network. We can revisit this when we get to implementing tasks related to perpetual data though.

I think one of the ways to do this is to make the `Account` struct generic, e.g. like this:

```rust
struct Account<ExtraData: Serialize + Deserialize> {
  maid_keys: MaidKeys,
  extras: ExtraData
}
```

I'm not sure if it needs to be _too_ generic though, but what it definitely needs is to be future-proof: what if we want to add more fields to the account struct and e.g. store some other root dir along with the access container? We still need to be able to deserialise existing accounts on the network.

But this question is also relevant for all other serialisable structs in SAFE Authenticator, and it should be a separate issue/discussion, so I'll leave it at that.
